<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\FileManagement.Domain\FileManagement.Domain.csproj" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="MiniExcel" Version="1.36.0" />
    </ItemGroup>
    
</Project>
